### ISSUE TITLE
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

### ISSUE THREAD

**Issue by MichaelMonashev** [clovaai/AdamP#17]
This problem rise after adding this line in train.py: `model = torch.nn.utils.convert_conv2d_weight_memory_format(model, torch.channels_last)`

```
Traceback (most recent call last):
  File "/home/xxxx/train.py", line 2203, in <module>
    main(0, world_size, ddp_init_file, args)
  File "/home/xxxx/train.py", line 400, in main
    train_acc, train_CE_loss, train_FL_loss, train_SmLbCE_loss, train_time = train(train_iterator, model, model_ema, criterion, optimizer, epoch, enable_OHEM, enable_CosineAnnealingLR, steps_per_epoch, accumulation_steps, rank, world_size, scaler)
  File "/home/xxxx/train.py", line 576, in train
    scaler.step(optimizer)
  File "/home/xxxx/.local/lib/python3.10/site-packages/torch/amp/grad_scaler.py", line 457, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "/home/xxxx/.local/lib/python3.10/site-packages/torch/amp/grad_scaler.py", line 352, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
  File "/home/xxxx/.local/lib/python3.10/site-packages/torch/optim/optimizer.py", line 487, in wrapper
    out = func(*args, **kwargs)
  File "/home/xxxx/.local/lib/python3.10/site-packages/adamp/adamp.py", line 91, in step
    perturb, wd_ratio = self._projection(p, grad, perturb, group['delta'], group['wd_ratio'], group['eps'])
  File "/home/xxxx/.local/lib/python3.10/site-packages/adamp/adamp.py", line 37, in _projection
    cosine_sim = self._cosine_similarity(grad, p.data, eps, view_func)
  File "/home/xxxx/.local/lib/python3.10/site-packages/adamp/adamp.py", line 27, in _cosine_similarity
    x = view_func(x)
  File "/home/xxxx/.local/lib/python3.10/site-packages/adamp/adamp.py", line 21, in _channel_view
    return x.view(x.size(0), -1)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
```

**Comment by bhheo** [comment]
Hi

Thank you for reporting. 

It seems the function `torch.nn.utils.convert_conv2d_weight_memory_format` changes GPU memory orders.

```python
model = nn.Conv2d(100,200,kernel_size=3, device='cuda')
model.weight.is_contiguous()
>> True
torch.nn.utils.convert_conv2d_weight_memory_format(model, torch.channels_last)
model.weight.is_contiguous()
>> False
```

Thus, we can't change the weight shape using `.view()` function

```python
model = nn.Conv2d(100, 200, kernel_size=3, device='cuda')
model.view(200, -1)
>> Good
torch.nn.utils.convert_conv2d_weight_memory_format(model, torch.channels_last)
model.view(200, -1)
>> Error
```

Because making the weight `contiguous` requires time-cost, I recommend you not to use `torch.nn.utils.convert_conv2d_weight_memory_format`
But if you have to use it, then replace following lines

https://github.com/clovaai/AdamP/blob/7f6f0383ff6ad3839d5c7f79f1db0a44c5a12fdb/adamp/adamp.py#L20-L24

to this
```python
    def _channel_view(self, x):
        if x.is_contiguous():
            return x.view(x.size(0), -1)
        else:
            return x.reshape(x.size(0), -1)

    def _layer_view(self, x):
        if x.is_contiguous():
            return x.view(1, -1)
        else:
            return x.reshape(1, -1)
```

This `.reshape` might prevent the error. But, it is slower than `.view()` function

**Comment by MichaelMonashev** [comment]
Here is rewritten version of AdamP and SGDP https://github.com/rwightman/timm/blob/main/timm/optim/adamp.py . Compare code pls. You will find many useful tricks and bug-fixes.

> This .reshape might prevent the error. But, it is slower than .view() function
 
`F.cosine_similarity()` - is slowest place in code. `reshape()` is not real problem.
